"""
mixtures.py

Defines a registry of dataset mixtures and weights for the Open-X Embodiment Datasets. Each dataset is associated with
a float "sampling weight"
"""

from typing import Dict, List, Tuple


# Dataset mixture name mapped to a list of tuples containing:
## {nakename: [(data_name, sampling_weight, robot_type)] }
DATASET_NAMED_MIXTURES = {

    "custom_dataset": [
        ("custom_dataset_name", 1.0, "custom_robot_config"),
    ],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],

    "libero_all": [
        ("libero_object_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_goal_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
                # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
    "libero_10_depth": [
        # ("libero_object_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        # ("libero_goal_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        # ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka_depth"),
                # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
    "libero_all_ration": [
        ("libero_object_no_noops_1.0.0_lerobot", 1.2, "libero_franka"),
        ("libero_goal_no_noops_1.0.0_lerobot", 1.4, "libero_franka"),
        ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.6, "libero_franka"),
                # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
     "libero_mv_all": [
        ("libero_object_no_noops_1.0.0_lerobot", 1.0, "libero_franka_mv"),
        ("libero_goal_no_noops_1.0.0_lerobot", 1.0, "libero_franka_mv"),
        ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka_mv"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka_mv"),
                # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
    "bridge": [
        ("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
    ],
    "bridge_rt_1": [
        ("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
        ("fractal20220817_data_0.1.0_lerobot", 1.0, "oxe_rt1"),
    ],

    "demo_sim_pick_place": [
        ("sim_pick_place", 1.0, "demo_sim_franka_delta_joints"),
    ],

    "custom_dataset": [
        ("custom_dataset_name", 1.0, "custom_robot_config"),
    ],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],

    "fourier_gr1_unified_1000": [
        ("gr1_unified.PnPBottleToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCanToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCupToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPMilkToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPPotatoToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPWineToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
    ],

    "BEHAVIOR_challenge": [
        ("BEHAVIOR_challenge", 1.0, "R1Pro"),
    ],


    "SO101_pick": [
        ("pick_dataset_name", 1.0, "SO101"),
    ],

    "arx_x5": [
        ("arx_x5", 1.0, "arx_x5"),
    ],

    "robotwin": [
        ("adjust_bottle", 1.0, "robotwin"),
        ("beat_block_hammer", 1.0, "robotwin"),
        ("blocks_ranking_rgb", 1.0, "robotwin"),
        ("blocks_ranking_size", 1.0, "robotwin"),
        ("click_alarmclock", 1.0, "robotwin"),
        ("click_bell", 1.0, "robotwin"),
        ("dump_bin_bigbin", 1.0, "robotwin"),
        ("grab_roller", 1.0, "robotwin"),
        ("handover_block", 1.0, "robotwin"),
        ("handover_mic", 1.0, "robotwin"),
        ("hanging_mug", 1.0, "robotwin"),
        ("lift_pot", 1.0, "robotwin"),
        ("move_can_pot", 1.0, "robotwin"),
        ("move_pillbottle_pad", 1.0, "robotwin"),
        ("move_playingcard_away", 1.0, "robotwin"),
        ("move_stapler_pad", 1.0, "robotwin"),
        ("open_laptop", 1.0, "robotwin"),
        ("open_microwave", 1.0, "robotwin"),
        ("pick_diverse_bottles", 1.0, "robotwin"),
        ("pick_dual_bottles", 1.0, "robotwin"),
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
        ("place_bread_basket", 1.0, "robotwin"),
        ("place_bread_skillet", 1.0, "robotwin"),
        ("place_burger_fries", 1.0, "robotwin"),
        ("place_can_basket", 1.0, "robotwin"),
        ("place_cans_plasticbox", 1.0, "robotwin"),
        ("place_container_plate", 1.0, "robotwin"),
        ("place_dual_shoes", 1.0, "robotwin"),
        ("place_empty_cup", 1.0, "robotwin"),
        ("place_fan", 1.0, "robotwin"),
        ("place_mouse_pad", 1.0, "robotwin"),
        ("place_object_basket", 1.0, "robotwin"),
        ("place_object_scale", 1.0, "robotwin"),
        ("place_object_stand", 1.0, "robotwin"),
        ("place_phone_stand", 1.0, "robotwin"),
        ("place_shoe", 1.0, "robotwin"),
        ("press_stapler", 1.0, "robotwin"),
        ("put_bottles_dustbin", 1.0, "robotwin"),
        ("put_object_cabinet", 1.0, "robotwin"),
        ("rotate_qrcode", 1.0, "robotwin"),
        ("scan_object", 1.0, "robotwin"),
        ("shake_bottle", 1.0, "robotwin"),
        ("shake_bottle_horizontally", 1.0, "robotwin"),
        ("stack_blocks_three", 1.0, "robotwin"),
        ("stack_blocks_two", 1.0, "robotwin"),
        ("stack_bowls_three", 1.0, "robotwin"),
        ("stack_bowls_two", 1.0, "robotwin"),
        ("stamp_seal", 1.0, "robotwin"),
        ("turn_switch", 1.0, "robotwin"),
    ],

    "robotwin_task1": [
        ("adjust_bottle", 1.0, "robotwin"),
    ],
    "robotwin_task2": [
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
    ],
    "robotwin_mix": [
        ("RoboTwin-Clean/adjust_bottle", 1.0, "robotwin50"),
        ("RoboTwin-Clean/beat_block_hammer", 1.0, "robotwin50"),
        ("RoboTwin-Clean/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("RoboTwin-Clean/blocks_ranking_size", 1.0, "robotwin50"),
        ("RoboTwin-Clean/click_alarmclock", 1.0, "robotwin50"),
        ("RoboTwin-Clean/click_bell", 1.0, "robotwin50"),
        ("RoboTwin-Clean/dump_bin_bigbin", 1.0, "robotwin50"),
        ("RoboTwin-Clean/grab_roller", 1.0, "robotwin50"),
        ("RoboTwin-Clean/handover_block", 1.0, "robotwin50"),
        ("RoboTwin-Clean/handover_mic", 1.0, "robotwin50"),
        ("RoboTwin-Clean/hanging_mug", 1.0, "robotwin50"),
        ("RoboTwin-Clean/lift_pot", 1.0, "robotwin50"),
        ("RoboTwin-Clean/move_can_pot", 1.0, "robotwin50"),
        ("RoboTwin-Clean/move_pillbottle_pad", 1.0, "robotwin50"),
        ("RoboTwin-Clean/move_playingcard_away", 1.0, "robotwin50"),
        ("RoboTwin-Clean/move_stapler_pad", 1.0, "robotwin50"),
        ("RoboTwin-Clean/open_laptop", 1.0, "robotwin50"),
        ("RoboTwin-Clean/open_microwave", 1.0, "robotwin50"),
        ("RoboTwin-Clean/pick_diverse_bottles", 1.0, "robotwin50"),
        ("RoboTwin-Clean/pick_dual_bottles", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_a2b_left", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_a2b_right", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_bread_basket", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_bread_skillet", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_burger_fries", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_can_basket", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_cans_plasticbox", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_container_plate", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_dual_shoes", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_empty_cup", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_fan", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_mouse_pad", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_object_basket", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_object_scale", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_object_stand", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_phone_stand", 1.0, "robotwin50"),
        ("RoboTwin-Clean/place_shoe", 1.0, "robotwin50"),
        ("RoboTwin-Clean/press_stapler", 1.0, "robotwin50"),
        ("RoboTwin-Clean/put_bottles_dustbin", 1.0, "robotwin50"),
        ("RoboTwin-Clean/put_object_cabinet", 1.0, "robotwin50"),
        ("RoboTwin-Clean/rotate_qrcode", 1.0, "robotwin50"),
        ("RoboTwin-Clean/scan_object", 1.0, "robotwin50"),
        ("RoboTwin-Clean/shake_bottle", 1.0, "robotwin50"),
        ("RoboTwin-Clean/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("RoboTwin-Clean/stack_blocks_three", 1.0, "robotwin50"),
        ("RoboTwin-Clean/stack_blocks_two", 1.0, "robotwin50"),
        ("RoboTwin-Clean/stack_bowls_three", 1.0, "robotwin50"),
        ("RoboTwin-Clean/stack_bowls_two", 1.0, "robotwin50"),
        ("RoboTwin-Clean/stamp_seal", 1.0, "robotwin50"),
        ("RoboTwin-Clean/turn_switch", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/adjust_bottle", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/beat_block_hammer", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/blocks_ranking_size", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/click_alarmclock", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/click_bell", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/dump_bin_bigbin", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/grab_roller", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/handover_block", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/handover_mic", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/hanging_mug", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/lift_pot", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/move_can_pot", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/move_pillbottle_pad", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/move_playingcard_away", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/move_stapler_pad", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/open_laptop", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/open_microwave", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/pick_diverse_bottles", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/pick_dual_bottles", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_a2b_left", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_a2b_right", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_bread_basket", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_bread_skillet", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_burger_fries", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_can_basket", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_cans_plasticbox", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_container_plate", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_dual_shoes", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_empty_cup", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_fan", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_mouse_pad", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_object_basket", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_object_scale", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_object_stand", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_phone_stand", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/place_shoe", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/press_stapler", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/put_bottles_dustbin", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/put_object_cabinet", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/rotate_qrcode", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/scan_object", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/shake_bottle", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/stack_blocks_three", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/stack_blocks_two", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/stack_bowls_three", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/stack_bowls_two", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/stamp_seal", 1.0, "robotwin50"),
        ("RoboTwin-convert/lerobot/turn_switch", 1.0, "robotwin50"),
    ],

    "multi_robot": [
        ("LEROBOT_LIBERO_DATA/libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        # ("OXE_LEROBOT_DATASET/bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
    ],
    "clean_the_table": [
        ("clean_the_table", 1.0, "real"),
    ],
    "put_toy_in_cabinet": [
        ("put_toy_in_cabinet", 1.0, "real"),
    ],
    "real_all": [
        ("insert_cube", 1.0, "real"),
        ("place_cup", 1.0, "real"),
        ("place_cylinder", 1.0, "real"),
        ("stack_block", 1.0, "real"),
    ],
}
